name: annotate-env
channels:
  - conda-forge
dependencies:
  - python=3.12.7
  - conda-forge::pandas=2.2.3
  - pip
  - pip:
    - matplotlib==3.8.2
    - opencv-python==4.9.0.80
    - numpy==1.26.4
    - ffmpeg
    - subprocess.run
    - scipy==1.12.0
    - librosa==0.10.1
    - pycollada
    - pillow
    - tk
    - customtkinter
